Add AppCenter and elementary Flatpak repos
elementary/os pull request #466
Opened 2021-04-12 16:49 UTC by danrabbit

2021-04-12 16:51 UTC, danrabbit commented
Assigned Blake for the actual location of the repo files

2021-04-12 16:58 UTC, davidmhewitt commented
I don't know whether there was a decision whether these should be system or user remotes. But, adding these here will make them system remotes. We'd need a different approach if we wanted one/both of these to be a user remote.

2021-04-12 17:38 UTC, btkostner commented
So, from what I know and understand, we have the elementary repo at `https://flatpak.elementary.io/elementary` which will be system, and then `https://flatpak.elementary.io/appcenter` which will be a user remote

2021-04-12 18:02 UTC, davidmhewitt commented
I think the solution to adding a user remote will be to add it to a working system and figure out what config file gets created in the home directory when that happens. It's a keyfile somewhere, I remember finding it once.

Then we can just add that to `/etc/skel` in the image.

2021-04-13 18:43 UTC, meisenzahl requested changes

2021-04-13 18:43 UTC, meisenzahl commented on etc/config/hooks/live/001-install-flatpaks.chroot
> +flatpak remote-add --if-not-exists elementary https://flatpak.elementary.io/elementary/elementary.flatpakrepo
```suggestion
flatpak remote-add --if-not-exists elementary https://flatpak.elementary.io/elementary.flatpakrepo
```

2021-04-13 18:43 UTC, meisenzahl commented on etc/config/hooks/live/001-install-flatpaks.chroot
> +flatpak remote-add --if-not-exists elementary https://flatpak.elementary.io/elementary/elementary.flatpakrepo
Shouldn't it be https://flatpak.elementary.io/elementary.flatpakrepo? https://flatpak.elementary.io/elementary/elementary.flatpakrepo returns a 404.

2021-04-13 20:35 UTC, btkostner approved these changes
Confirmed working on my local computer now. We should be good to merge.

2021-04-13 20:36 UTC, btkostner commented
Can I get one other person to confirm they are able to add the repo and install platform or calculator. I was getting a runtime error with calculator, but install worked fine.

2021-04-13 20:43 UTC, danrabbit commented
@btkostner Yup! I was able to add this repo and install calculator. Congrats! You are the man!

2021-04-13 20:43 UTC, merged