Issue Template: build system form
elementary/os pull request #573
Opened 2021-11-24 19:40 UTC by danrabbit

Does everything here make sense?

2021-11-25 12:35 UTC, davidmhewitt requested changes
From the description, we're only expecting to receive issues here when there has been an issue building an image, or possibly when a daily image has failed to install (like the case you had yesterday).

But currently the questions are more worded around, which image are you installing, rather than which image did you try to build, which I think possibly needs clarifying?

2021-11-25 12:35 UTC, davidmhewitt commented on .github/ISSUE_TEMPLATE/build_system.yml
> +        1. Open System Settigns → About → Report a Problem
```suggestion
        1. Open System Settings → About → Report a Problem
```

2021-11-25 12:35 UTC, davidmhewitt commented on .github/ISSUE_TEMPLATE/build_system.yml
> +      label: OS Version
I think maybe we need a distinction here between the version of the image people are building, and the operating system they're building it on?

Yes, it's docker, but we've had issues of people trying to build it on Windows/macOS and not being able to as a result of platform specific stuff.

2021-11-25 12:35 UTC, davidmhewitt commented on .github/ISSUE_TEMPLATE/build_system.yml
> +      description: The processor architechture of the image you're installing
```suggestion
      description: The processor architecture of the image you're installing
```

Typo, but, would this be better as something like the variant of the image you're building/using?

If we're saying this is only for reporting problems with the build scripts, then people shouldn't be reporting issues here if they're installing the image?

2022-03-07 18:48 UTC, cassidyjames commented on .github/ISSUE_TEMPLATE/build_system.yml
> +      required: true
@davidmhewitt how about

```suggestion
  - type: dropdown
    attributes:
      label: Host OS
      description: The host OS you are using to build elementary OS
      options:
        - elementary OS 6.x (Stable, from our homepage)
        - elementary OS 6.x (Early Access)
        - elementary OS 7.x (Early Access)
        - Windows
        - macOS
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Image Version
      description: The version of elementary OS you are attempting to build
      options:
        - OS 6.x stable
        - OS 6.x daily
        - OS 7.x daily
    validations:
      required: true
```

2024-11-23 18:35 UTC, stsdc commented
I have replaced dropdowns with a textareas, since the version of elementary os changes. And also there are too many variations of different OSes and their versions. It removes unnecessary burden to update this template every OS release.

2025-01-05 14:38 UTC, stsdc approved these changes

2025-01-05 16:27 UTC, alainm23 approved these changes

2025-01-05 18:42 UTC, merged